### ISSUE TITLE
make a rest service with flask

### ISSUE THREAD

**Issue by ghost** [KeremZaman/semantic-sh#1]
Hi,

Hope you are all well !

Do you think it is possible to make a restful web service of semantic-sh ? or to dockerize it ?

Cheers,
X

**Comment by KeremZaman** [comment]
Hi,

I didn't need such a service when I was coding but it can be a useful feature. It will be done in the next update.

**Comment by ghost** [comment]
Thanks @KeremZaman 

It would be awesome as I work on paper2code.com and it would be useful to find similar abstracts.

When do you think you can find 10 minutes to do it ? 
I am so excited by the next update :-)

**Comment by KeremZaman** [comment]
I added simple api server. It can be run standalone or by a WSGI container. I hope you'll get good results, don't avoid to give further feedbacks!

Closed with b4219dcff85e3634bd53426a10474c00c736f092

**Comment by ghost** [comment]
Hi,

Thanks for this !

I am dockerizing it and making it ready for cpu/gpu deploy ! Will make a PR during the day !

Preview: https://github.com/x0rzkov/semantic-sh

Thanks again !

Cheers,
X
